on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: pylint --disable=C0114,C0115,C0116 --exit-zero src/**/*.py src/*.py
      - name: Check Pylint score
        run: |
          pylint_score=$(pylint --disable=all --enable=metrics --output-format=text src/**/*.py src/*.py | grep 'Raw metrics' | awk '{print $4}')
          if (( $(echo "$pylint_score < 8" | bc -l) )); then
            echo "Pylint score is below 8. Blocking commit."
            exit 1
          else
            echo "Pylint score is acceptable."
          fi