on:
  push:
      paths:
        - 'src/**'
        - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
      - name: Install dependencies
        run: |
          rye config --set-bool behavior.use-uv=true
          rye pin 3.11.1
          rye sync
      - name: Analysing the code with pylint
        run: rye run pylint --disable=C0114,C0115,C0116 --exit-zero src/**/*.py src/*.py
      - name: Check Pylint score
        run: |
          pylint_score=$(pylint --disable=all --enable=metrics --output-format=text src/**/*.py src/*.py | grep 'Raw metrics' | awk '{print $4}')
          if (( $(echo "$pylint_score < 8" | bc -l) )); then
            echo "Pylint score is below 8. Blocking commit."
            exit 1
          else
            echo "Pylint score is acceptable."
          fi