name: Compile thesis to PDF

on:
  push:
      paths:
        - 'thesis/**'
        - '.github/workflows/thesis.yml'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker://pandoc/latex:2.9
        with:
          args: thesis/*.md -o "thesis/tesi_federico_aguzzi.pdf"

          
      - uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: thesis