on:
  push:
      paths:
        - 'src/**'
        - 'src/tests/**'
        - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Install the latest version of rye
        uses: phi-friday/install-rye@v1.4
        with:
          rye_version: "latest"
          python_version: 3.12
          use_uv: true
      - name: Install dependencies
        run: |
          rye sync --no-lock
      - name: Run unit tests on the code
        run: rye run python -m unittest ${GITHUB_WORKSPACE}/src/tests/*.py
      - name: Check test results
        run: |
          test_result=$(python3 -m unittest ${GITHUB_WORKSPACE}/src/tests/*.py |& grep "FAILED" | wc -w)
          if (( $(echo "$test_result") == 0 )); then
            echo "Tests passed. Commit approved."
          else
            echo "Tests failed. Blocking commit."
            exit 1
          fi