on:
  push:
      paths:
        - 'src/**'
        - 'src/tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
      - name: Install dependencies
        run: rye sync
      - name: Run unit tests on the code
        run: rye run python -m unittest ${GITHUB_WORKSPACE}/src/tests/*.py
      - name: Check test results
        run: |
          test_result=$(python3 -m unittest ${GITHUB_WORKSPACE}/src/tests/*.py |& grep "FAILED" | wc -w)
          if (( $(echo "$test_result") == 0 )); then
            echo "Tests passed. Commit approved."
          else
            echo "Tests failed. Blocking commit."
            exit 1
          fi